"""update training program attribute

Revision ID: 027b467c6515
Revises: 0bb79b70562a
Create Date: 2024-03-12 11:22:02.593462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '027b467c6515'
down_revision: Union[str, None] = '0bb79b70562a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_program', sa.Column('cvr_compression', sa.Integer(), nullable=True))
    op.add_column('training_program', sa.Column('cvr_ventilation', sa.Integer(), nullable=True))
    op.drop_column('training_program', 'per_compression')
    op.drop_column('training_program', 'per_ventilation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_program', sa.Column('per_ventilation', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('training_program', sa.Column('per_compression', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('training_program', 'cvr_ventilation')
    op.drop_column('training_program', 'cvr_compression')
    # ### end Alembic commands ###
