"""create certification table

Revision ID: 0630cdf41358
Revises: 4ae33508679c
Create Date: 2024-03-19 14:28:38.474343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0630cdf41358'
down_revision: Union[str, None] = '4ae33508679c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issued_date', sa.DATETIME(), server_default=sa.text('now()'), nullable=True),
    sa.Column('training_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], name=op.f('fk_certification_training_id_training')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certification'))
    )
    op.create_index(op.f('ix_certification_id'), 'certification', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certification_id'), table_name='certification')
    op.drop_table('certification')
    # ### end Alembic commands ###
