"""fix table relationship

Revision ID: 14f24f5aaf1d
Revises: 033ea1c4fc39
Create Date: 2024-03-13 10:45:02.906035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f24f5aaf1d'
down_revision: Union[str, None] = '033ea1c4fc39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_trainings_download_options_user_id'), 'trainings_download_options', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trainings_download_options_user_id'), table_name='trainings_download_options')
    # ### end Alembic commands ###
