"""modify column length

Revision ID: 4ae33508679c
Revises: c9c309e66877
Create Date: 2024-03-19 11:59:27.416535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4ae33508679c'
down_revision: Union[str, None] = 'c9c309e66877'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_certification_id', table_name='certification')
    op.drop_table('certification')
    op.alter_column('organization_content', 's3_key',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('organization_content', 'file_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('training_program_content', 's3_key',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('training_program_content', 'file_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=300),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('training_program_content', 'file_name',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('training_program_content', 's3_key',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('organization_content', 'file_name',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('organization_content', 's3_key',
               existing_type=sa.String(length=300),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.create_table('certification',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('manikin_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('issued_date', mysql.DATETIME(), nullable=True),
    sa.Column('training_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['training_id'], ['training.id'], name='fk_certification_training_id_training'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_certification_id', 'certification', ['id'], unique=False)
    # ### end Alembic commands ###
