"""add certifications template table

Revision ID: 97995f1d6f27
Revises: fa8e440d1cd6
Create Date: 2024-03-12 16:39:29.634575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97995f1d6f27'
down_revision: Union[str, None] = 'fa8e440d1cd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('manikin_type', sa.String(length=50), nullable=True),
    sa.Column('organization_name', sa.String(length=50), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_certifications_template_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications_template'))
    )
    op.create_index(op.f('ix_certifications_template_id'), 'certifications_template', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_certifications_template_id'), table_name='certifications_template')
    op.drop_table('certifications_template')
    # ### end Alembic commands ###
