"""create certification table

Revision ID: ad841b8c58d9
Revises: 0630cdf41358
Create Date: 2024-03-19 16:57:15.283783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad841b8c58d9'
down_revision: Union[str, None] = '0630cdf41358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('certification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_certification_user_id_user'), 'certification', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_certification_user_id_user'), 'certification', type_='foreignkey')
    op.drop_column('certification', 'user_id')
    # ### end Alembic commands ###
