"""add organization content table

Revision ID: fa8e440d1cd6
Revises: 074f31d9c69a
Create Date: 2024-03-12 15:34:01.238265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa8e440d1cd6'
down_revision: Union[str, None] = '074f31d9c69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_content',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=100), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_organization_content_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization_content'))
    )
    op.create_index(op.f('ix_organization_content_id'), 'organization_content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_content_id'), table_name='organization_content')
    op.drop_table('organization_content')
    # ### end Alembic commands ###
